name: Deploy Frontend

on:
  push:
    branches:
      - master  # 监听 main 分支
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ 安装依赖 & 构建前端项目
      - name: Install dependencies & build
        run: |
          npm install
          npm run build  # 生成 dist-prod 目录
          cd dist-prod  # 这里改成 dist-prod
          zip -r dist.zip ./*  # 压缩成 dist.zip
      

      # 4️⃣ 上传 dist.zip 到服务器的 temp/ 目录
      - name: Upload to Server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist-prod/dist.zip"  # 这里改成 dist-prod
          target: "/work/projects/yudao-ui-admin/temp/"

      # 5️⃣ 远程执行部署脚本
      - name: Execute deployment script on server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            chmod +x /work/projects/yudao-ui-admin/deploy-frontend.sh
            cd /work/projects/yudao-ui-admin
            ./deploy-frontend.sh
